-- DROP DATABASE Library;

CREATE DATABASE Library;

USE Library;

CREATE TABLE Author (
    SSN VARCHAR(64) PRIMARY KEY UNIQUE,
    Name VARCHAR(64) NOT NULL
);

CREATE TABLE Book (
    ISBN VARCHAR(64) PRIMARY KEY,
    Title VARCHAR(64) NOT NULL,
    Genre VARCHAR(64) NOT NULL,
    Grade INT
);

CREATE TABLE WrittenBy (
    Book_ISBN VARCHAR(64) NOT NULL,
    Author_SSN VARCHAR(64) NOT NULL,
    FOREiGN KEY (Book_ISBN) REFERENCES Book(ISBN),
    FOREiGN KEY (Author_SSN) REFERENCES Author(SSN)
);
